version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://rajveer:RYUiFj0ywuMHbSK64voxVuBNAczwo5RU@dpg-d847e20g4nts73euu48g-a.oregon-postgres.render.com/myapp_oqzr
      DB_USER: rajveer
      DB_PASSWORD: RYUiFj0ywuMHbSK64voxVuBNAczwo5RU
      DB_HOST: dpg-d847e20g4nts73euu48g-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: myapp_oqzr
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: your_jwt_secret_key_change_this
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: ../rajveer_patel_cgs_task_frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
